import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import Provider from "@/context/Provider";
import Link from "next/link";
import Navigation from "@/app/components/Navigation";
import Footer from "@/app/components/Footer";
import { authOptions } from "@/utils/authoptions";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TourneyPro",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  console.log("server session", session);
  return (
    <html lang="en">
      <Provider session={session}>
        <body className={inter.className}>
          <Navigation></Navigation>
          {children}
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
