import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import Provider from "@/context/Provider";
import Link from "next/link";
import Logout from "./logout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();
  console.log('session', session)
  return (
    <html lang="en">
      <Provider session={session}>
        <body className={inter.className}>
          <nav>
            {session && <Logout />}
            {!session && <Link href="/login">Login</Link>}
          </nav>
          {children}
        </body>
      </Provider>
    </html>
  );
}
